### ISSUE TITLE
pnpm bundle 失败

### ISSUE THREAD

**Issue by donotlb** [blocklet/create-blocklet#103]
环境: 
- macOS
- @blocklet/cli 1.7.8
- pnpm 6.32.4

操作步骤: 

1. pnpm create blocklet xxx
2. pnpm install
3. pnpm bundle

![image](https://user-images.githubusercontent.com/24994263/165670314-453d6cd7-e5f3-4842-a421-04b0fcf6e435.png)

![image](https://user-images.githubusercontent.com/24994263/165670093-95a2fab5-8597-46bc-8731-ff92cbc9a29e.png)

**Comment by donotlb** [comment]
试了下 yarn, install + yarn bundle 是 OK 的

**Comment by LancelotLewis** [comment]
bug 是由于之前旧版的 eslint-config 导致的，目前已经全面升级到了新版的 eslint-config
问题已经不存在了
