### ISSUE TITLE
create blocklet 生成的项目用的 API_PORT 会导致 deploy 到 server 无法启动

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/create-blocklet#106]
![截屏2022-05-10 下午3 22 55](https://user-images.githubusercontent.com/12446758/167572349-d3693d3d-c0d1-4d43-aeae-b8a6b882d79b.png)

server 用的是 blocklet_port.

**Comment by wangshijun** [comment]
这个得尽快 fix，不然影响 coding test
