### ISSUE TITLE
create-blocklet 实现类似create-react那样自动升级dependency

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#108]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/41923/169742014-f54bb561-c5c0-43b0-9750-b6e37a62917e.png">

这个被create react app作为自己的一个亮点。

不过的确所有生成类型的应用，都有版本升级的头痛问题，如果能自动升级dependency，的确会让工具更令人欢迎

**Comment by mave99a** [comment]
这个也许不是create-react的特性？ 只是用了npm和package.json 的特性？

**Comment by wangshijun** [comment]
我们生成的项目如果是 react，里面刚好用了 react-scripts，而从整体看，项目本身的依赖很多，而且会因为项目内业务需要出现各种各种的 dependency，相比而言，blocklet-cli 和 react-scripts 更像。而 cli 是可以随时升级的。
