### ISSUE TITLE
create-blocklet 产生的模版里要把logo，favicon这些尽量只采用一个文件，否则用户以后要更改的地方太多

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#110]
目前有： 

- 根目录下有logo.png, 用于blocklet.md里引用
- public 下有logo，favicon

这些应该用同一个文件，如优化需要多个版本，应该在build的时候产生不同的文件。 

不要让用户去update 好多地方。

**Comment by mave99a** [comment]
这个实践下来是非常重要的小问题，我们不能让dev在这些小问题上浪费时间，最终导致的是他们用我们开发出的产品显得观感不佳 （很多人会用很丑陋的默认icon）

**Comment by wangshijun** [comment]
此外，这个应该是 blocklet cli 的一个自工具，根据 logo.png 自动产生 iconset

**Comment by wangshijun** [comment]
cc @skypesky
