### ISSUE TITLE
默认创建的 logo 不应该有 padding

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#113]
会影响 store 里面的展示效果

![Screen Shot 2022-05-30 at 11 46 33](https://user-images.githubusercontent.com/719985/170913593-32ee056d-5078-49be-819a-448c12b364c5.png)

**Comment by frmachao** [comment]
默认的 logo 没有 padding  @wangshijun 
<img width="616" alt="image" src="https://user-images.githubusercontent.com/22849231/174053530-45889299-3f10-4f8c-80b3-1d3317ef5e7e.png">

**Comment by wangshijun** [comment]
我指的是图片内的 padding，那个立方体应该撑满图片

**Comment by frmachao** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/22849231/174267409-465a3f70-4867-47cb-8ad4-36bececa7421.png">

**Comment by frmachao** [comment]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/22849231/174273049-54d102b4-aaf3-483a-a721-a99377b3962a.png">

**Comment by LancelotLewis** [comment]
边框貌似太粗了，这是自己画的？

**Comment by frmachao** [comment]
> 边框貌似太粗了，这是自己画的？

这是最新的样子，PR 已更新 @LancelotLewis 
![image](https://user-images.githubusercontent.com/22849231/174317363-7160aae3-a523-4844-94a1-674ec5c78dc1.png)
