### ISSUE TITLE
我的 vscode 配置了使用空格符，直接跑 create blocklet 生成的项目会报 lint 错

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/create-blocklet#12]
![截屏2021-08-03 下午5 22 04](https://user-images.githubusercontent.com/12446758/127992511-faa15830-c9e5-475a-af3e-b2226b4bed05.png)

**Comment by NateRobinson** [comment]
https://github.com/blocklet/create-blocklet/issues/8

**Comment by NateRobinson** [comment]
@LancelotLewis 我好像找到原因了，是因为模板项目的.prettierrc 文件里面没有指定：
`"useTabs": false`，我手动添加之后，reload 项目就可以了。

**Comment by LancelotLewis** [comment]
fixed by https://github.com/blocklet/create-blocklet/commit/a13bfd413b9e1be2026c48033469e94b942723b4
