### ISSUE TITLE
首页给出一个明显的链接到blocklet 和blocklet doc 的站点

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#126]
首页给出一个明显的链接到blocklet 和blocklet doc 的站点 以帮助用户了解什么是blocklet 

（不过blocklet 本身的站点 和doc 也需要建立起来，可以先为place holder，逐渐改进）

参考下 create react的站点，链接一个react的首页

**Comment by wangshijun** [comment]
在 Footer 里面会有，在 Header 里面也应该有

**Comment by wangshijun** [comment]
![Screen Shot 2022-08-15 at 08 16 02](https://user-images.githubusercontent.com/719985/184560223-b61cd220-a837-4378-8527-d2f9208bb6b4.png)
