### ISSUE TITLE
需要设计一个 Create Blocklet 自己的 Logo

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/create-blocklet#129]
目前使用的是 Blocklet Server 的 Logo，应该要设计一个 Create Blocklet 自己的 Logo

https://page-site-n3l-18-180-145-193.ip.abtnet.io/

**Comment by dosthcool** [comment]
应该使用Blocklet的logo作为文档的logo。
参考：https://docs.github.com/cn

<img width="181" alt="截屏2022-06-30 14 50 15" src="https://user-images.githubusercontent.com/24971257/176611398-ec0efe49-aba7-4541-955b-23b922bdbf9f.png">

**Comment by dosthcool** [comment]
几个方向：
因为Blocklet属于其品牌的重要元素，感觉直接拿过来主图标更直接，他和blocklet pages一样单独就是一个应用。

下面方案：
1. 使用黑色版本logo，可以解释为极客。
2. 使用品牌logo，文字部分直接用lato字体。
3. 两行式，遵循其他产品中的logo样式，但是读起来顺序会有一些奇怪。


![Frame 1161](https://user-images.githubusercontent.com/24971257/176649040-b7557676-0733-46f7-9043-7791daaf58a3.png)

**Comment by LancelotLewis** [comment]
暂用第三个方案

**Comment by dosthcool** [comment]
review 建议：
<img width="688" alt="截屏2022-07-11 17 31 51" src="https://user-images.githubusercontent.com/24971257/178234422-dd8c7489-4fc3-4d32-b039-3f6ae42033b3.png">

设计方案：
左侧的方案比较适合这类action在前面的logo，右侧带有从属关系的logo不太合适。

<img width="686" alt="截屏2022-07-11 17 31 25" src="https://user-images.githubusercontent.com/24971257/178234348-50196fa6-55af-4471-870e-11d52bbd9db6.png">

两种logo已更新：
导航上用横向的，其他地方可以自行选择合适的logo。
<img width="670" alt="截屏2022-07-11 17 37 19" src="https://user-images.githubusercontent.com/24971257/178235487-6c602cfd-16b4-4405-ba2c-6efeb03781d7.png">

**Comment by dosthcool** [comment]
因为blocklet需要一个正方形App icon，所以前置的logo需要改成一个和【Create】相关的，万一之后有别的【XXX Blocklet】还要换一个icon，以下是一些方案设计：
<img width="791" alt="截屏2022-07-14 15 21 10" src="https://user-images.githubusercontent.com/24971257/178925090-7fda56b6-c3a1-4181-a3f4-5032985316b0.png">
<img width="409" alt="截屏2022-07-14 15 43 51" src="https://user-images.githubusercontent.com/24971257/178930098-41a4cb1a-731f-4637-a3c9-26a34d7ef06b.png">

**Comment by mave99a** [comment]
这个目前的加号版本还可以

**Comment by mave99a** [comment]
第三或四个可以给 正在开发的xmarkcomponent builder
