### ISSUE TITLE
当系统变为黑暗模式时，docs 站点的内容部分自动应用了黑暗模式的样式

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/create-blocklet#130]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/8749615/176453011-5ac4ea3f-d28f-4b55-bd8c-c17deee453a7.png">

**Comment by wangshijun** [comment]
得看看渲染 markdown 的组件，可能有自动切换的逻辑

**Comment by LancelotLewis** [comment]
fixed by https://github.com/ArcBlock/xmark-next/commit/32171f15408580b53c9c570146dd95b31495a279
