### ISSUE TITLE
切换到英文之后 URL 出现异常

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#131]
复现步骤：

- 打开：https://0f48a5df-znkjt5vbgnezh4p6v4dsaye61e7pxxn3vk4j.did.abtnet.io/
- 切换到英文
- 点击 docs，出现 404
- 再继续点击，出现更长的 url

<img width="626" alt="Screen Shot 2022-07-04 at 09 38 29" src="https://user-images.githubusercontent.com/719985/177070615-b94effac-0132-43d5-bb4d-cd55a6fda982.png">

<img width="670" alt="Screen Shot 2022-07-04 at 09 38 47" src="https://user-images.githubusercontent.com/719985/177070609-55ba4634-7b00-430e-ab32-ccf100ac3b92.png">

**Comment by LancelotLewis** [comment]
fixed by https://github.com/ArcBlock/xmark-next/commit/c898f4aa7ec9dd31e04973b2ce5166ec6f48b86a
