### ISSUE TITLE
create-blocklet docs 的几点改进建议

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#133]
1. 需要说明下什么事 Blocklet Service，什么情况下该使用，该如何使用应该链接到别处去。还应该增加 Notification Service
2. Best Practice 可以不区分 dapp 类型，里面应该包括如下内容：
  - 让 blocklet 足够简单，方便组合
  - 让 blocklet 能够挂载在相对路径下
  - 控制 blocklet bundle 的体积，说明下目前最大限制 500M
  - 替换 blocklet 的 logo，方的，256 * 256
  - 更新 blocklet.md，必要的时候支持多语言
  - 其他的 https://www.notion.so/arcblock/HackWeek-FAQ-db8b805c20184890bc725c67e7d3d746#a5caf6a40ceb4382902871d18b5a8d30
3. 增加 FAQ 或者 trouble shooting，澄清一些误解，比如
  - 如何发布到 store？
  - 如何通过开发 blocklet 赚钱？
  - 其他框架的支持？
  - 其他能想到的...

**Comment by mave99a** [comment]
这个可以按仕军这个思路把文档框架搭起来 然后慢慢填入

**Comment by LancelotLewis** [comment]
最佳实践可以改为以下几种类别：
- 普通免费 blocklet -> auth-demo
- 普通付费 blocklet -> payment-demo
- 组合型 blocklet -> component demo
- 通知服务 blocklet -> notification-demo

这样还能利用上我们已有的各类 demo

**Comment by wangshijun** [comment]
不再适用，其他几个文档站有覆盖
