### ISSUE TITLE
Create Blocklet 流程 Bug Bash 20220711

### ISSUE THREAD

**Issue by FireTable** [blocklet/create-blocklet#137]
### 前置工作
0. 拉取 `blocklet-server` 的 `dev` 分支 (原因: 新的特性 process.env.BLOCKLET_DEV_MOUNT_POINT 未发版)
1. 根目录执行 `make build`
2. 前往本地 `bn-dev-data <你的路径>` 目录, 执行 `bn server stop` & `bn server start`
3. 后续部署 blocklet 的时候, 请使用 `bn`

### 主要流程
0. 执行 `bn create`
    - 版本应该大于:  <img width="408" alt="image" src="https://user-images.githubusercontent.com/24667209/178170730-c9cec819-bb31-4e60-a138-75891d46ac67.png">
1. 选择自己负责的框架
   - [ ] react (craco) @wangshijun  @linchen1987 
   - [ ] vue2 (@vue/cli) @polunzh 
   - [ ] vue3 (vite)  @donotlb @kirakiray
   - [ ] solidjs (vite) @frmachao 
   - [ ] svelte (vite) @skypesky 
   - [ ] nextjs @LancelotLewis
2. 完成init, cd到目录, 安装依赖 `yarn`
3. 测试 `bn dev`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
4. 测试 `bn dev --component --app-did <your-blocklet-did>`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
5. 测试 `yarn run deploy`
   - [ ] 是否部署到本地 
   - [ ] 挂载组件 - 通过URL添加 - 输入 `file:// + <Meta-Path>` 是否能正常挂载
           - 比如: `file:///Users/FireTable/Code/ArcBlock/create-blocklet/examples/vite-test/.blocklet/release/blocklet.json`
   - [ ] 测试是否都能正常打开访问

### 注意事项
vite相关的模板, 需要访问一下hmr服务器, 详情请看console

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/24667209/177951344-89bb003f-6c0d-46b8-afd0-8336a564a35a.png">

**Comment by LancelotLewis** [comment]
- [ ] nextjs @LancelotLewis
2. 完成init, cd到目录, 安装依赖 `yarn`
3. 测试 `bn dev`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
4. 测试 `bn dev --component --app-did <your-blocklet-did>`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
5. 测试 `yarn run deploy`
   - [ ] 是否部署到本地 
   - [ ] 挂载组件 - 通过URL添加 - 输入 `file:// + <Meta-Path>` 是否能正常挂载
           - 比如: `file:///Users/FireTable/Code/ArcBlock/create-blocklet/examples/vite-test/.blocklet/release/blocklet.json`
   - [ ] 测试是否都能正常打开访问

**Comment by wangshijun** [comment]
2. 完成init, cd到目录, 安装依赖 `yarn`
3. 测试 `bn dev`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
4. 测试 `bn dev --component --app-did <your-blocklet-did>`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
5. 测试 `yarn run deploy`
   - [ ] 是否部署到本地 
   - [ ] 挂载组件 - 通过URL添加 - 输入 `file:// + <Meta-Path>` 是否能正常挂载
           - 比如: `file:///Users/FireTable/Code/ArcBlock/create-blocklet/examples/vite-test/.blocklet/release/blocklet.json`
   - [ ] 测试是否都能正常打开访问

**Comment by frmachao** [comment]
## Create Blocklet 流程主要内容

### 前置工作
0. 拉取 `blocklet-server` 的 `dev` 分支 (原因: 新的特性 process.env.BLOCKLET_DEV_MOUNT_POINT 未发版)
1. 根目录执行 `make build`
2. 前往本地 `bn-dev-data <你的路径>` 目录, 执行 `bn server stop` & `bn server start`
3. 后续部署 blocklet 的时候, 请使用 `bn`

### 主要流程
0. 执行 `bn create`
    - 版本应该大于:  <img width="408" alt="image" src="https://user-images.githubusercontent.com/24667209/178170730-c9cec819-bb31-4e60-a138-75891d46ac67.png">
1. 选择自己负责的框架
   - [ ] solidjs (vite) @frmachao 
2. 完成init, cd到目录, 安装依赖 `yarn`
3. 测试 `bn dev`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
4. 测试 `bn dev --component --app-did <your-blocklet-did>`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
5. 测试 `yarn run deploy`
   - [ ] 是否部署到本地 
   - [ ] 挂载组件 - 通过URL添加 - 输入 `file:// + <Meta-Path>` 是否能正常挂载
           - 比如: `file:///Users/FireTable/Code/ArcBlock/create-blocklet/examples/vite-test/.blocklet/release/blocklet.json`
   - [ ] 测试是否都能正常打开访问

### 注意事项
vite相关的模板, 需要访问一下hmr服务器, 详情请看console

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/24667209/177951344-89bb003f-6c0d-46b8-afd0-8336a564a35a.png">

**Comment by donotlb** [comment]
0. 执行 `bn create`
    - 版本应该大于:  <img width="408" alt="image" src="https://user-images.githubusercontent.com/24667209/178170730-c9cec819-bb31-4e60-a138-75891d46ac67.png">
1. 选择自己负责的框架
   - [ ] react (craco) @wangshijun  @linchen1987 
   - [ ] vue2 (@vue/cli) @polunzh 
   - [ ] vue3 (vite)  @donotlb @kirakiray
   - [ ] solidjs (vite) @frmachao 
   - [ ] svelte (vite) @skypesky 
   - [ ] nextjs @LancelotLewis
2. 完成init, cd到目录, 安装依赖 `yarn`
3. 测试 `bn dev`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
4. 测试 `bn dev --component --app-did <your-blocklet-did>`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
5. 测试 `yarn run deploy`
   - [ ] 是否部署到本地 
   - [ ] 挂载组件 - 通过URL添加 - 输入 `file:// + <Meta-Path>` 是否能正常挂载
           - 比如: `file:///Users/FireTable/Code/ArcBlock/create-blocklet/examples/vite-test/.blocklet/release/blocklet.json`
   - [ ] 测试是否都能正常打开访问

**Comment by kirakiray** [comment]
### 主要流程
0. 执行 `bn create`
    - 版本应该大于:  <img width="408" alt="image" src="https://user-images.githubusercontent.com/24667209/178170730-c9cec819-bb31-4e60-a138-75891d46ac67.png">
1. 选择自己负责的框架
   - [ ] vue3 (vite) @kirakiray
2. 完成init, cd到目录, 安装依赖 `yarn`
3. 测试 `bn dev`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
4. 测试 `bn dev --component --app-did <your-blocklet-did>`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
5. 测试 `yarn run deploy`
   - [ ] 是否部署到本地 
   - [ ] 挂载组件 - 通过URL添加 - 输入 `file:// + <Meta-Path>` 是否能正常挂载
           - 比如: `file:///Users/FireTable/Code/ArcBlock/create-blocklet/examples/vite-test/.blocklet/release/blocklet.json`
   - [ ] 测试是否都能正常打开访问

**Comment by polunzh** [comment]
0. 执行 `bn create`
    - 版本应该大于:  <img width="408" alt="image" src="https://user-images.githubusercontent.com/24667209/178170730-c9cec819-bb31-4e60-a138-75891d46ac67.png">
1. 选择自己负责的框架
   - [ ] vue2 (@vue/cli) @polunzh 
2. 完成init, cd到目录, 安装依赖 `yarn`
3. 测试 `bn dev`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
4. 测试 `bn dev --component --app-did <your-blocklet-did>`
   - [ ] 页面渲染是否正常
   - [ ] 更新代码是否会自动hmr刷新
5. 测试 `yarn run deploy`
   - [ ] 是否部署到本地 
   - [ ] 挂载组件 - 通过URL添加 - 输入 `file:// + <Meta-Path>` 是否能正常挂载
           - 比如: `file:///Users/FireTable/Code/ArcBlock/create-blocklet/examples/vite-test/.blocklet/release/blocklet.json`
   - [ ] 测试是否都能正常打开访问
