### ISSUE TITLE
[BUG]: create blocklet docs 侧边栏高亮表现不一致

### ISSUE THREAD

**Issue by FireTable** [blocklet/create-blocklet#148]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/24667209/178434569-333b0ed8-936d-4953-ae26-fc9d18c030fa.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/24667209/178434606-34311c88-908e-4421-a5a0-da6987e3a644.png">

https://www.createblocklet.dev/docs/zh/best-practice/demo-api

集成服务 + FAQ: 点击子项目, 会高亮parentTitle
快速上手 + 最佳实践: 点击子项目, 不会高亮parentTitle

**Comment by LancelotLewis** [comment]
fixed
