### ISSUE TITLE
[Hold] croco.config.js 中webpack默认配置会导致dev环境打包后的静态资源引用地址错误

### ISSUE THREAD

**Issue by ee07b577** [blocklet/create-blocklet#150]
/post/:id 地址匹配 post组件。
<img width="577" alt="image" src="https://user-images.githubusercontent.com/1484821/178884311-f3b09bf6-4468-40b7-83b7-065378929131.png">
从任意地址link到 /post/:id地址可以正常打开，但是在 /post/:id 地址原地刷新，会出现以下错误：
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/1484821/178884235-a24b7df3-1eeb-4546-9584-cadff1c2c37d.png">
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/1484821/178884537-743c662f-8e57-4991-998f-f629e24b23d6.png">
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/1484821/178884600-15d99cac-62a8-4e07-bfd4-11c36a91358f.png">

注释掉这一行配置后，
<img width="820" alt="image" src="https://user-images.githubusercontent.com/1484821/178883934-94346b45-0a7f-4cdf-858d-09b4fb6dc839.png">
bundle.js文件的路径正常了
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/1484821/178883998-51784c9b-6732-4cfa-a677-7cf444459652.png">

**Comment by FireTable** [comment]
晚一点会处理

**Comment by LancelotLewis** [comment]
后期计划将 react 模板的 webpack 替换为 vite，vite-plugin-blocklet 不会出现这个问题

**Comment by FireTable** [comment]
close, 已经迁移完毕
