### ISSUE TITLE
创建的 react 静态项目无法使用 @did-connect/react

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#151]
关联问题：https://github.com/facebook/create-react-app/issues/11756
解决方案：https://www.alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5

稍后加上 repo

**Comment by wangshijun** [comment]
更好的解决方案是这个：https://www.npmjs.com/package/node-polyfill-webpack-plugin

目测我们所有的项目都需要

**Comment by wangshijun** [comment]
@LancelotLewis @FireTable 这个我们应该 bake 在配置中还是放到 FAQ 中更好？

**Comment by LancelotLewis** [comment]
如果模板中都加上 did-connect 示例功能（增加一个按钮，唤起 did-connect）就应该直接加入配置项

否则在当前写在 did-connect 的文档中就好

**Comment by wangshijun** [comment]
最新的模板小坑还不少

<img width="834" alt="Screen Shot 2022-07-15 at 09 25 05" src="https://user-images.githubusercontent.com/719985/179128065-667e35b8-84ca-43c6-9b87-79fdd2ea2142.png">

解决方案：https://www.npmjs.com/package/node-polyfill-webpack-plugin 加上 console 到 excludedAliases

**Comment by wangshijun** [comment]
还有这个问题：https://stackoverflow.com/questions/55821078/disable-eslint-that-create-react-app-provides/59249839#59249839

之前以为无法扩展 eslint 配置，但是现在发现是可以的

**Comment by LancelotLewis** [comment]
> 之前以为无法扩展 eslint 配置，但是现在发现是可以的

我们目前的 eslint 配置都是独立在 `eslintrc.js` 中的，以上方案是开启在 `package.json` 中配置 eslint 的功能？

**Comment by LancelotLewis** [comment]
上一次在 blocklet store 中切换 vite 的工作可以在下个季度再尝试一次了
related https://github.com/ArcBlock/xmark-next/issues/94

**Comment by wangshijun** [comment]
react-fullstack fixed in https://github.com/blocklet/create-blocklet/commit/15f04cf96b6a15309b37454ec4f7e49ec253f3c6

**Comment by LancelotLewis** [comment]
所有模板均已切换为 vite
