### ISSUE TITLE
vite3 对 hmr 做了改进，不需要再写我们 hack 的 hmr 插件了

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/create-blocklet#153]
需要在插件中根据 vite 版本做出不同的处理

**Comment by FireTable** [comment]
> createBlockletPlugin({ disableHmr: true }),
可以配这个参数禁用掉 hmr 插件

一会在 blender 试验下

**Comment by LancelotLewis** [comment]
vite 插件当前不支持直接获取到 vite 的版本，需要通过读取跟目录 pkg 文件的方式，或者要自己去 node_modules 文件夹下去寻找，以上都不是特别好的方案。

所以最终决定通过手动传入 `version: 2` 来指定为适配 vite2 的行为（默认适配的是 vite3）
