### ISSUE TITLE
创建出来的 xmark 项目里面缺少一些东西

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#166]
- 最大的问题是不能直接打包为 blocklet
- 其次是版本号管理：可以集成 zhanghan 在 xmark 下封装的？
- 其次是我们常用的 github actions，比如 pr-title-lint、version-bump-check 等
- 其他：.gitignore 忽略掉 .blocklet 文件夹，.editorconfig 等

**Comment by frmachao** [comment]
.editorconfig  不应该忽略吧？

- [ ] 常用的 github actions，比如 pr-title-lint、version-bump-check 等。
- [ ] 版本号管理，目前已有，但是不太好用。
