### ISSUE TITLE
create blocklet 站点首页介绍支持多个framework那里应该有个logo墙

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#168]
create blocklet 站点首页介绍支持多个framework那里应该有个logo墙展示我们支持的各种框架的logo

因为这些logo 是让开发者熟悉的，也是信心的关键，应该重点强调。

**Comment by wangshijun** [comment]
@LancelotLewis 目前 Logo Wall 该用 SectionAvatarList？还是有别的

**Comment by LancelotLewis** [comment]
使用 LogoWall

**Comment by wangshijun** [comment]
> 使用 LogoWall

LogoWall 没有 storybook，可以尽快加个

**Comment by wangshijun** [comment]
![Screen Shot 2022-08-22 at 15 46 00](https://user-images.githubusercontent.com/719985/185867427-aae71258-096e-469a-98ac-7a513ec652b6.png)
