### ISSUE TITLE
想把一个card2 放在list 里失败了

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#169]
想把card2 放在list里，这样形成一个卡片的list，但无论怎么放都不现实

```
          - name: Card2
            title: I am title
            img: https://s3.bmp.ovh/imgs/2022/07/27/76d7fe8f2a8295bc.jpg
            desc: I am desc
```

storybook里有个专门的section card list，但感觉list 既然有就应该能在下面list更复杂的东西

**Comment by mave99a** [comment]
本想回这个效果的： 

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/41923/185055990-adfd86ef-a0b3-42fa-8109-ab806f4c980e.png">

**Comment by LancelotLewis** [comment]
track in https://github.com/ArcBlock/xmark-next/issues/300
