### ISSUE TITLE
create blocklet 是否能帮助用户检查一下ABT Node的环境

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#17]
create blocklet 是否能帮助用户配置和检查一下ABT Node的环境，这样让下面开发和运行更流畅。 

注意可以是本地有abt node, 也可以是配置使用远程的abt node, 或docker里的。 

几种情况： 

- 没有配置可用的abt node
- abt node没有安装
- abt node 没有运行
- abt node版本太低不兼容
- 设置不正确 （如果能检查出来）
- 没有权限部署 

理想中能支持本地安装的abt node, 远程 的 abt node, docker里的abtnode等 （这些情况可能是有交集的）

**Comment by LancelotLewis** [comment]
- [ ] 需要检测有没有安装 abtnode 
   - 没有配置可用的abt node
   - abt node 没有安装
 
- [ ] 需要检测版本是否符合要求
   - abt node版本太低不兼容

> 后期支持远程部署后，添加部署权限检测
