### ISSUE TITLE
支持创建 monorepo 类型的种子项目

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#182]
这样更加容易开始一些复杂的项目，我目前的思路：

- 每个 template 在其 package.json 或其他文件里面声明自己是否支持组合，目前的大部分应该是支持的
- create 时的选择应该支持多选，如果用户多选了，就创建为 monorepo，使用 lerna 去管理
- 如果用户多选了，需要让用户显示制定主应用，并为其他应用配置好 dev:child
- monorepo 类型的项目 readme、ci、npm script 和普通项目应该都有所不同

**Comment by frmachao** [comment]
> create 时的选择应该支持多选，如果用户多选了，就创建为 monorepo

这样设计会有一个问题，我们现在的模板本身分成 dapp static api 三大类，用户进入某一类后多选的话，只能选择这个大类下面的。

如果这样设计：
选择模板类型时： 分成 dapp static api  monorepo 四大类，当用户选择多选的话，就可以从所有的模板中进行选择；
多选的默认上限为4（）

**Comment by wangshijun** [comment]
另1个思路是，现在的创建流程可以优化下，去掉类型的选择，把类型展示在每个选项的前面，比如

- [static] creat-react-app
- [dapp] express + create-reat-app

然后给模版选择加上搜索即可。这样就可以不受大类的限制。整体交互也比较简单，不需要用户思考多步骤，选择完就可以了。

**Comment by frmachao** [comment]
> 如果用户多选了，需要让用户显示制定主应用，并为其他应用配置好 dev:child

- 让用户选择一个模板作为主 blocklet
- 多个 blocklet 中 blocklet.yml 的名称规则是 仓库名+模板名，比如 monorepo-react-dapp 、monorepo-blocklet-page

**Comment by wangshijun** [comment]
可以在每个  template 的 package.json 里面配置模板的元信息
比如 composePriority，来标注优先级
用户选择多个模板之后，按 composePriority 从高到低排序，取最高的作为主 app
