### ISSUE TITLE
bug bash 2022-09-21

### ISSUE THREAD

**Issue by frmachao** [blocklet/create-blocklet#187]
## 测试计划：
creata blocklet 在 v0.4.50 版本新增支持创建 monorepo 类型项目的功能:

- create 时的选择支持多选
    + 如果用户多选了，就创建为 monorepo，使用 lerna + yarn 去管理
    + 如果用户多选了，需要让用户显示制定主应用，并为其他应用配置好 dev:child、deploy:child

测试计划如下：

能创建成功、能成功在本地启动、能成功打包、能成功部署并启动

### React 相关模板 @frmachao 
- [ ] [dapp]react + blocklet page + doc site
- [ ] [dapp]react+gunjs +  [static]react
- [ ] [dapp] nextjs +  [static]vue3

### Vue 相关模板 @FireTable 
- [ ] [dapp]vue3 + blocklet page  + doc site
- [ ] [static]vue2 + express.js + blocklet page 

### 其他相关模板 @LancelotLewis 

- [ ] [dapp] solidjs  +  blocklet page + doc site
- [ ] [static] svelte +  express.js + blocklet page

**Comment by FireTable** [comment]
### Vue 相关模板 @FireTable 
- [ ] [dapp]vue3 + blocklet page  + doc site
- [ ] [static]vue2 + express.js + blocklet page

**Comment by frmachao** [comment]
### React 相关模板 @frmachao 
- [ ] [dapp]react + blocklet page + doc site
- [ ] [dapp]react+gunjs +  [static]react
- [ ] [dapp] nextjs +  [static]vue3

**Comment by LancelotLewis** [comment]
### 其他相关模板 @LancelotLewis
- [ ] [dapp] solidjs + blocklet page + doc site
- [ ] [static] svelte + express.js + blocklet page
