### ISSUE TITLE
Unable to start the generated Blocklet

### ISSUE THREAD

**Issue by rahul0208** [blocklet/create-blocklet#19]
When working with node :16  the blocket causes the following errors : 
- The generation reports an error but still generated the blocklet code.
``` js
TypeError: Cannot read property 'replace' of undefined
    at getDid (file:///root/.npm/_npx/4daa8ae53dba528c/node_modules/create-blocklet/index.js:353:24)
    at file:///root/.npm/_npx/4daa8ae53dba528c/node_modules/create-blocklet/index.js:284:17
    at init (file:///root/.npm/_npx/4daa8ae53dba528c/node_modules/create-blocklet/index.js:295:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

- ABT Node initialization fails to find nginx routing service.
```
root@12cfd7537d70:/data/abtnode# abtnode init --mode=debug
abtnode init v1.4.6
? Are you sure to initialize a ABT Node instance in the current directory(/data/abtnode) Yes
✖ No supported routing engine found, please install a supported routing engine first.
⚠ Supported routing engines are: nginx
```

PFA the [output.log](https://github.com/blocklet/create-blocklet/files/6966331/output.log)

**Comment by rahul0208** [comment]
> @rahul0208 Can't reproduce this error, I test with:
> 
> ```
> MacOS
> docker latest
> node:alpine latest (16.6.1)
> @abtnode/cli 1.4.6
> ```
> 
> Maybe you can give me more information about enviroment
```
Host :  MacOS
$ docker -v
Docker version 20.10.7, build f0df350
root@12cfd7537d70:/data/abtnode# node -v
v16.6.1
root@12cfd7537d70:/data/abtnode# abtnode -V     
1.4.6
```

**Comment by rahul0208** [comment]
I have attached the entire sequence of commands and their outputs in the log. Please let me know if I need to do things differently.

**Comment by LancelotLewis** [comment]
fixed by https://github.com/blocklet/create-blocklet/commit/d47407aa199dc75a45526918fafa81033a3dfd21
