### ISSUE TITLE
[ Task ]: vite系列插件, 应该内置 svg-loader

### ISSUE THREAD

**Issue by FireTable** [blocklet/create-blocklet#195]
https://github.com/pd4d10/vite-plugin-svgr

我们的项目一般会配置一些icon, 经常是svg的, 内置一个loader会让我们引用起来比较自然

**Comment by FireTable** [comment]
目前是vite模板里面, 安装了 svg-loader 的依赖
后续支持插件之后可以去除

**Comment by LancelotLewis** [comment]
建议由项目自己添加，因为它是专用于 react 的，不适合放在通用的插件中
