### ISSUE TITLE
react template 安装依赖报错

### ISSUE THREAD

**Issue by donotlb** [blocklet/create-blocklet#199]
![image](https://user-images.githubusercontent.com/24994263/192261881-81e82fa3-6e1b-4289-851a-dc7a7efde304.png)

原因好像是 craco 6.x 不支持 CRA 5

![image](https://user-images.githubusercontent.com/24994263/192262178-89ede754-c5c3-4167-b678-b78c60a24bb0.png)

---

可能的解决方案: 

- craco 7.x (alpha)
- craco -> vite

**Comment by donotlb** [comment]
`yarn` 安装依赖正常, `npm install` 会报错

**Comment by wangshijun** [comment]
直接切换到 vite 的？

**Comment by FireTable** [comment]
close, 已经迁移完毕 craco => vite
