### ISSUE TITLE
生成的 blocklet 里面 ocap/arcblock/abtnode/blocklet scope 下的依赖应该指向 latest

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#2]
确保每次都用的最新版，减少每次依赖发完版都要手动升级这个 repo 的麻烦。

另外，因为可能 blocklet/sdk 和项目声明的 ocap/arcblock scope 的依赖版本可能不同步，建议在 package.json 中增加 resolution 字段来确保使用的是最新版，参考：https://github.com/blocklet/ocap-playground/blob/main/package.json#L151

**Comment by LancelotLewis** [comment]
`warning Resolution field "latest" has an invalid version entry and may be ignored`

resolutions 字段中配置 version 为 latest 不会被识别，最好是能手动去指定 resolution 的版本。
另外 resolution 字段也无法被 npm 识别，目前只能在 yarn 下使用，在 npm 中使用需要借助 https://www.npmjs.com/package/npm-force-resolutions 来实现。
