### ISSUE TITLE
生成的 react+express 项目，子页面打开会失败

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/create-blocklet#216]
![截屏2022-10-09 10 56 10](https://user-images.githubusercontent.com/12446758/194749058-65fbac08-77f4-4bcb-a257-d1c2696a2e5e.png)

更改 craco 配置后可以恢复正常：
### 更改前
```js
 const webpackConfig = whenDev
   ? {
       configure: {
         output: {
           publicPath: '', // When the dev mode as component, this line required
         },
       },
       plugins,
     }
   : { plugins };
```

### 更改后
```js
const webpackConfig = whenDev
  ? {
      // configure: {
      //   output: {
      //     publicPath: '', // When the dev mode as component, this line required
      //   },
      // },
    }
  : {};
```

**Comment by wangshijun** [comment]
@FireTable 请你来支持下吧

**Comment by FireTable** [comment]
> @FireTable 请你来支持下吧

这个项目是用 create-blocklet 创建的?
要不我们把 react craco 的支持移除了? 现在 react vite , 感觉已经挺稳定了

**Comment by FireTable** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/24667209/194791336-37d298fc-2c1a-469a-a806-ec5f0dd32fe0.png">

会把这三个react项目的craco全部升级成为vite

**Comment by FireTable** [comment]
- [x]  create-blocklet 模板更新
- [x]  nate 项目从 craco 到 vite

close issue, 后续有问题在做跟进
