### ISSUE TITLE
[ Bug ]: vite 模板 blocklet deploy后,  不支持动态加载 modulepreload 包

### ISSUE THREAD

**Issue by FireTable** [blocklet/create-blocklet#219]
### 问题

在 `tweet-token` 迁移到vite时候发现
目前在vite中, 如果用了 `React.lazy`  / vite自带的 `import.meta.glob` 语法

dynamic import的包, `blocklet deploy`后, 会变成以下这样
```
<link rel="modulepreload" as="script" crossorigin="" href="/.blocklet/proxy/z8iZoLRKRXHzqdJ2vFZEi4H5UXT9ADsurxZRK/assets/admin.e7b77da7.js">
```

其中应该是 crossorigin="" /  rel="modulepreload" 属性影响vite加载包的功能, 导致无法加载dynamic的包
<img width="962" alt="image" src="https://user-images.githubusercontent.com/24667209/194866521-ab3eb3af-e65a-4004-8490-7c33e4394d11.png">

查看network发现, 并没有附带 header.referer 参数, 导致被 `blocklet-server` 拦截了
<img width="938" alt="image" src="https://user-images.githubusercontent.com/24667209/194866588-4139f37e-94fe-4c73-b874-6bb46962e4d0.png">

// 无referer test
<img width="878" alt="image" src="https://user-images.githubusercontent.com/24667209/194866817-b7fe296d-0ba5-4ceb-8e79-fbdc9e18821e.png">

// 有referer test
<img width="972" alt="image" src="https://user-images.githubusercontent.com/24667209/194866959-ab0feea1-e1e9-4d23-90f7-2327f4b5573f.png">

* 现状: 只能用单文件打包方式

### 解决思路
1. blocklet server 不拦截 header.referer === undefined
    - 与`晨哥`沟通后, 发现 referer 参数是需要的, 不能这样玩
2. 配置vite项目
    - <img width="1090" alt="image" src="https://user-images.githubusercontent.com/24667209/194869384-e31ffaad-96f0-4f5e-8458-6761b430b927.png">
    - 也有其它人的 issue 需要这个功能: https://github.com/vitejs/vite/issues/6648

### 为什么没进行下去
在翻 vite 文档的时候, 发现英文文档 5小时前 更新了一个参数 `build.modulePreload.resolveDependencies`, 感觉有戏

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/24667209/194868013-37d83a25-94b0-4f7f-b28f-8081e72c0923.png">

<img width="855" alt="image" src="https://user-images.githubusercontent.com/24667209/194868370-fa8b3734-c99c-4839-abe8-ff00c0726e27.png">

所以先做问题记录, 后续再做修复

**Comment by FireTable** [comment]
https://github.com/vitejs/vite/pull/9938

vite 相关 PR

**Comment by LancelotLewis** [comment]
在 3.2 beta 中设置 build.modulePreload: false 禁用掉 modulepreload 可以成功

**Comment by LancelotLewis** [comment]
> 发现使用 link modulepreload 加载 js 文件天然就没有 referer

是 chrome 内核的 bug，firefox 实测没有问题

在 chrome 下的表现是 link modulepreload 加载 css 有带 referer，加载 js 文件不带 referer
而在 firefox 下的表现是 link modulepreload 加载 css 和 js 都会携带 referer

考虑到 modulepreload 在不同浏览器下的实现是不统一的，所以禁用 modulepreload 可能是目前最省心的选择

**Comment by FireTable** [comment]
军哥的 vcm 也遇到同样的问题

后续支持后, 需要通知 vcm / tweet-token

**Comment by LancelotLewis** [comment]
3.2.0 发布了
https://github.com/vitejs/vite/releases/tag/v3.2.0

**Comment by yumanman88** [comment]
请问，这个修改modulepreload的crossorigin是已经在3.2.0实现了吗

**Comment by FireTable** [comment]
> 请问，这个修改modulepreload的crossorigin是已经在3.2.0实现了吗

https://cn.vitejs.dev/config/build-options.html#build-modulepreload ✅

**Comment by LancelotLewis** [comment]
> 请问，这个修改modulepreload的crossorigin是已经在3.2.0实现了吗

在新版的 blocklet-server，不再对静态资源有 referer 限制，所以目前不需要修改 build.modulePreload 也可以实现正常加载拆包的应用
