### ISSUE TITLE
create-blocklet 应支持 windows 环境下使用

### ISSUE THREAD

**Issue by frmachao** [blocklet/create-blocklet#225]
当前的 create-blocklet(v0.4.73 ) 对 windows 的支持并不好 ，为了更好的支持 windows ，需要做的事：

- [x] 单个 blocklet 里面的 bump-version 也改为 monorepo 相同的，makefile 在 windows 下不太友好 /how-to/manage-blocklet-release
- [x] monorepo 类型的项目初始化，使用的 make init 脚本应改为 npm script
- [x] single 类型的项目 dev 和 deploy
- [ ]  monorepo 类型的项目 dev 和 deploy

**Comment by wangshijun** [comment]
track in blocklet-server
