### ISSUE TITLE
[Feedback] 末尾增加 What's next

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#226]
链接到用户创建完应用接下来会关注的话题

- developer.blocklet.io how 里面的部分链接
- 创建单个、组合型应用

---
#### Document Details
* AppId: zNKkQuRidtsBVskb8oDXKVh5PpM5uD5PKxim
* Content: [快速上手](https://www.createblocklet.dev/docs/zh/quick-start/hello-blocklet)
* Content Source: [website/docs/pages/quick-start/hello-blocklet/index.zh.mdx](https://github.com/blocklet/create-blocklet/tree/main/website/docs/pages/quick-start/hello-blocklet/index.zh.mdx)
* Version: 0.1.0

**Comment by frmachao** [comment]
已处理： https://www.createblocklet.dev/docs/en/quick-start/hello-blocklet#whats-next
