### ISSUE TITLE
[ Bug ]: 迁移到 vite 模板, global / buffer / process 在 window 中丢失的问题

### ISSUE THREAD

**Issue by FireTable** [blocklet/create-blocklet#232]
目前解决方式比较hacker, 后续考虑用插件处理, 先做问题记录

global 丢失

```
# vite.config.js 增加 以下配置

optimizeDeps: {
      esbuildOptions: {
        // Node.js global to browser globalThis
        define: {
          global: 'globalThis',
        },
      },
    },

```

buffer / process 丢失

```
index.html header 增加 以下配置

<script type="module">
      import { Buffer } from 'buffer';
      import process from 'process';
      window.Buffer = Buffer;
      window.process = process;
</script>

```

**Comment by LancelotLewis** [comment]
在 https://github.com/blocklet/vote 中进行了测试，使用 [vite-plugin-ngmi-polyfill](https://www.npmjs.com/package/vite-plugin-ngmi-polyfill) 可实现目标效果

**Comment by LancelotLewis** [comment]
这个可以在 FAQ 中进行描述，不适合写在模板中

**Comment by skypesky** [comment]
> 在 [blocklet/vote](https://github.com/blocklet/vote) 中进行了测试，使用 [vite-plugin-ngmi-polyfill](https://www.npmjs.com/package/vite-plugin-ngmi-polyfill) 可实现目标效果

@LancelotLewis 

这个方案对 did-storage 无效，我用了永卓的方案解决了 `global 丢失` 的问题.

**Comment by LancelotLewis** [comment]
周末再跟进测试一下 did-storage

**Comment by LancelotLewis** [comment]
方案已集成到 vite-plugin-blocklet 中
https://www.createblocklet.dev/docs/en/faq#error-not-found-global-buffer-process
