### ISSUE TITLE
[Feedback] 类型应该是yaml？ 但显示是shell

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#243]
[Enter feedback here]

<img width="888" alt="image" src="https://user-images.githubusercontent.com/41923/199370772-380e27a8-2839-44a4-8b17-9cb80e64ee97.png">

---
#### Document Details
* AppId: zNKkQuRidtsBVskb8oDXKVh5PpM5uD5PKxim
* Content: [自定义你的应用](https://www.createblocklet.dev/docs/zh/how-to/customize-blocklet)
* Content Source: [website/docs/pages/how-to/customize-blocklet/index.zh.mdx](https://github.com/blocklet/create-blocklet/tree/main/website/docs/pages/how-to/customize-blocklet/index.zh.mdx)
* Version: 0.1.0

**Comment by frmachao** [comment]
已处理：https://www.createblocklet.dev/docs/en/how-to/customize-blocklet
