### ISSUE TITLE
[Feedback] “注意”这种类型的渲染是不是不是我们期望的？

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#244]
[Enter feedback here]

<img width="935" alt="image" src="https://user-images.githubusercontent.com/41923/199371436-44b3c7fc-f04c-46e0-a802-75c43554aa77.png">

可能我们期望的是：
<img width="334" alt="image" src="https://user-images.githubusercontent.com/41923/199372494-add28ba4-47ad-48fd-b543-b06de1b11331.png">

github的：
https://github.com/community/community/discussions/16925

---
#### Document Details
* AppId: zNKkQuRidtsBVskb8oDXKVh5PpM5uD5PKxim
* Content: [自定义你的应用](https://www.createblocklet.dev/docs/zh/how-to/customize-blocklet)
* Content Source: [website/docs/pages/how-to/customize-blocklet/index.zh.mdx](https://github.com/blocklet/create-blocklet/tree/main/website/docs/pages/how-to/customize-blocklet/index.zh.mdx)
* Version: 0.1.0

**Comment by wangshijun** [comment]
需要切换到 `:::Alert` 语法

**Comment by frmachao** [comment]
已处理： https://www.createblocklet.dev/docs/en/how-to/customize-blocklet#configure-the-blocklets-logo
