### ISSUE TITLE
[hold] bundle:client 中去掉 PUBLIC_URL

### ISSUE THREAD

**Issue by linchen1987** [blocklet/create-blocklet#26]
在支持了 ip-dns-domain endpoint 后
- 普通 blocklet build 时不需要指定 PUBLIC_URL
- 只有 component blocklet build 时才需要 `PUBLIC_URL='/.blocklet/proxy/xxxxx`,

建议：
- 增加一个选项：是否是 component blocklet，默认 false
- 是component blocklet 时，在package.json 中 bundle:client 和现在保持一致，不是 component blocklet 时，在package.json 中 bundle:client 不指定 PUBLIC_URL

优先级低

**Comment by LancelotLewis** [comment]
这里存在一个问题，某些 blocklet 既可以是独立部署的，也可以作为 component blocklet 来部署，例如：NFT-Store，它在开发之初就是作为独立部署存在的，后来是支持了成为 component blocklet

**Comment by mave99a** [comment]
是否是默认blocklet 既可以独立部署，也可以作为component. 除非这个blocklet 设计为只能作为component. 

我想建议**任何blocklet都设计为可以立刻部署、立刻独立运行的**。 如果本身只能做component, 可以运行一个简单的说明页面，而不是出错。 如果有必须的配置，可以运行一个页面，就是说明缺少哪些配置。 这个create-blocklet就可以把这些页面直接生成好，甚至逻辑直接处理好。 

console里仍然可以展示某些blocklet 缺少配置，但是仍然可以直接运行起来（但显示一个警告，提醒用户去配置）

这样设计的话，可用性会更好。

**Comment by linchen1987** [comment]
独立运行 blocklet 和 component blocklet 的一个区别：
- 独立运行 blocklet: 默认不支持 mount 在相对路径下，静态资源不用走 `/.blocklet/proxy`
- component blocklet: 必须支持 mount 在相对路径下，静态资源需要走 `/.blocklet/proxy`

原则：
- 在支持了 ip-dns-domain endpoint 后，独立运行的blocklet 不应该 mount 在相对路径下，因为会带来安全问题
- 如果 blocklet 不mount在相对路径下，那么静态资源不需要也不应在走 `/.blocklet/proxy`

假设使用 create-blocklet 创建的大部分 blocklet 都是独立运行的 blocklet, 那么希望默认配置应该只支持作为独立运行的 blocklet

**Comment by LancelotLewis** [comment]
概念描述：
- root blocklet 指的是可以独立部署的 blokclet
- component blocklet 指的是作为 children 存在的 blocklet
- 指定了`PUBLIC_URL='/.blocklet/proxy/xxxxx`的 blocklet 既可以作为 root blocklet 也可以作为 component blocklet，建议将 `blocklet.yml` 中的 `interfaces.prefix` 设置为 `*` 或特定的路径，例如 `/session`
- 未指定 `PUBLIC_URL` 的 blocklet 只能作为 root component，并且建议将 `blocklet.yml` 中的 `interfaces.prefix` 设置为 `/`

需求描述：
- 在 create-blocklet 中添加一个配置项，用于生成 root blocklet 和 component blocklet 不同的代码
- 不指定 `PUBLIC_URL` 的 blocklet 静态资源不用走 /.blocklet/proxy，会有更好的性能，并且由于大部分 blocklet 都不会作为 component blocklet 提供服务，所以这类 blocklet 直接配置成 root blocklet 更为合适
- 在需要配置成 component blocklet 的情况下，可以通过 create-blocklet 的一个选项来生成带有 `PUBLIC_URL='/.blocklet/proxy/xxxxx` 配置的代码

**Comment by LancelotLewis** [comment]
目前不会影响任何流程，暂时 hold

**Comment by LancelotLewis** [comment]
目前已统一为使用 vite-plugin-blocklet 来自动添加 build 后的前缀，保持使用带 did 的静态资源地址
