### ISSUE TITLE
通过 create 创建的项目，blocklet.yml 的 did 错误

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/create-blocklet#299]
![截屏2023-10-07 17 17 31](https://github.com/blocklet/create-blocklet/assets/12446758/4301d661-155c-4003-b4e0-8dda8733662b)

**Comment by NateRobinson** [comment]
blocklet init v1.16.17-beta-8cacb9b3

**Comment by NateRobinson** [comment]
![image](https://github.com/blocklet/create-blocklet/assets/12446758/ffbcceec-4109-4fb5-a283-62f038d099ea)

**Comment by LancelotLewis** [comment]
本地未能复现，看补充应该是连接 store 时超时导致的

此时应该中断整个过程，而不是继续

**Comment by NateRobinson** [comment]
![截屏2023-10-07 22 03 17](https://github.com/blocklet/create-blocklet/assets/12446758/2987b06d-798f-47bd-a353-466db3326ed9)
除了 timeout ，还有网络链接断开的异常情况。

**Comment by FireTable** [comment]
候选者也遇到了

复现不走:
create-blocklet - 选择模板 - 弹出 DID Connect - 不 connect 或者注册别的 DID wallet - 程序会自动成功，但是 did 是错误的

感觉生成 blocklet.yml 的时候, 应该拿到 did 后再验证一下 did?

<img width="408" alt="image" src="https://github.com/blocklet/create-blocklet/assets/24667209/927ca6fe-c827-403c-8d86-8df4a172c4c0">

**Comment by Merbeleue** [comment]
请问这个问题解决了吗？

**Comment by LancelotLewis** [comment]
> 请问这个问题解决了吗？

@Merbeleue 新的版本对这个流程做了优化，不会再出现这个问题
