### ISSUE TITLE
[BUG] The dependency conflict when create a static react app

### ISSUE THREAD

**Issue by tianzhich** [blocklet/create-blocklet#305]
After creating a static react app using this [template](https://github.com/blocklet/create-blocklet/blob/main/packages/create-app/templates/react-static/package.json). I got the error when install the dependency:
```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: blocklet-profile-demo@0.1.0
npm ERR! Found: vite@4.5.1
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.4.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.0.0" from @vitejs/plugin-react@2.2.0
npm ERR! node_modules/@vitejs/plugin-react
npm ERR!   dev @vitejs/plugin-react@"^2.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

We might need to update the version of [`@vitejs/plugin-react`](https://github.com/blocklet/create-blocklet/blob/main/packages/create-app/templates/react-static/package.json#L48) to at least [`@3`](https://www.npmjs.com/package/@vitejs/plugin-react/v/3.0.0?activeTab=code), make it compatible with `vite@4`.

**Comment by LancelotLewis** [comment]
fixed
