### ISSUE TITLE
能支持保存后端代码时重启调试，但不要重启 vite 插件，节省 coding -> preview 时间

### ISSUE THREAD

**Issue by li-yechao** [blocklet/create-blocklet#328]
问题：
- 目前的 ts 项目（js 项目应该也是类似情况）保存了后端代码后会触发 nodemon 热更新（重启后端）
- 前端代码是通过 vite 的 middleware 模式挂载到后端的，后端重启也会重启 vite middleware，需要重启完成后刷新页面才能继续 preview/debug

方案：
能否把两者分开，或者说加一个前置的 server，把 vite middleware 放到前置 server 中，前置 server 应该是 lib 提供的，不存在热更新问题。开发过程中后端代码热更新仅影响接口调用。

**Comment by li-yechao** [comment]
by @LancelotLewis 

可以尝试一下：https://github.com/axe-me/vite-plugin-node

**Comment by LancelotLewis** [comment]
0.8.8 版本以上已支持
