### ISSUE TITLE
新建的 react+express+typescript 项目 dev 时出现 __vite_hmr__ 426 问题

### ISSUE THREAD

**Issue by donotlb** [blocklet/create-blocklet#332]
![image](https://github.com/blocklet/create-blocklet/assets/24994263/147cb8a8-3e8e-48eb-9070-599afeceee65)

不知道和配置了 `BLOCKLET_DEV_MOUNT_POINT=/dp` 环境变量有没有关系, 感觉路径里出现 2 次 mountpoint - `/dp/dp/`

**Comment by LancelotLewis** [comment]
这个是开发环境中正常的请求，不需要关心它
