### ISSUE TITLE
基于 react + express.js 模板创建 blocklet 时终端有报错，但是并没有影响走完流程

### ISSUE THREAD

**Issue by polunzh** [blocklet/create-blocklet#334]
Blocklet Server CLI: v1.16.29-beta-ec04c755

![image](https://github.com/blocklet/create-blocklet/assets/4244426/4ce0b82f-12eb-496f-aa68-bdf63c115697)

**Comment by LancelotLewis** [comment]
这个问题已处理，目前不会出现这个错误消息
