### ISSUE TITLE
[Bug]: modify the default logo to meet the new bundle requirements

### ISSUE THREAD

**Issue by ymzuiku** [blocklet/create-blocklet#371]
### Describe the bug

Bundle blocked by logo size

### Reproduction Steps

1. create-blocklet
2. run  npm run bundle

### Observed Behavior

blocklet bundle v1.16.33-beta-20241107-065332-b20666d2
✔ Parsing blocklet meta from: /home/pillar/source/simple-blocklet-test
✔ Blocklet components verify success!
ℹ Bundling in compact mode for blocklet z2qa2F9EuwCRu89GXqRAhW9yMAms5CNvFsonQ...
.   Creating blocklet bundle in .blocklet/bundle...(node:69140) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
⚠ No screenshots found!

⚠ Blocklet bundle failed! Please check the following errors about logo:
✖ The logo(logo.png) just supports 256x256, but got 320x320.
ℹ You can run the command "blocklet dev studio" to help you generate more standard images.

### Expected Behavior

compilable

**Comment by wangshijun** [comment]
@ymzuiku please upgrade your @blocklet/cli to latest version and verify again.

**Comment by ymzuiku** [comment]
new @blocklet/cli@beta version fixed this issue
