### ISSUE TITLE
建议添加一个仅含后端代码的 Blocklet 模板

### ISSUE THREAD

**Issue by polunzh** [blocklet/create-blocklet#40]
两个场景：
1. Node.js 服务端的 Coding Test 只要求实现 API, 现在的模板可能会给面试者带来麻烦
1. 我们自己有几个没有前端的 Blocklet: IP Echo DNS, DID DNS，所以后面可能会有需求

**Comment by mave99a** [comment]
有道理，免得用户误认为blocklet就是前端

**Comment by LancelotLewis** [comment]
duplicate #36
