### ISSUE TITLE
为create-blocklet 我们值得专门一个web站点 + 文档

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#44]
为create-blocklet 我们值得专门一个web站点 + 文档

因为这个工具很重要。 

如同 https://create-react-app.dev

我们可以用 https://create.blocklet.dev

**Comment by wangshijun** [comment]
@LancelotLewis 接下来 did-connect、xmark 自身的站点都会跟 create-react-app 的站点比较像，我们可以开始着手这个事情，反过来 push xmark 具备写首页、layout、docs 的能力。

**Comment by mave99a** [comment]
下面也准备逐渐把核心部件开源（Q3 OKR）， 我们需要比较好的文档来帮助别人理解我们的代码，这样才能贡献create-blocklet

**Comment by LancelotLewis** [comment]
目前 create-blocklet 是 public 的

**Comment by wangshijun** [comment]
https://www.createblocklet.dev/
