### ISSUE TITLE
初始化之后 blocklet 启动并不是用的 blocklet dev？

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#5]
这个需要想办法 enforce，不然 auth-service 没法用，思路如下：

- 把 abtnode cli 作为生成项目的 dev dependency
- abtnode 已经支持在任意路径下初始化启动，比如 `abtnode start -a`
- 启动 blocklet 之前确保 node 已经起来了，可以看看 start-server-and-test

**Comment by LancelotLewis** [comment]
- `@abtnode/cli` 依赖包太大了，单独安装这个包后 `node_modules` 达到了 310MB
- `-a` 参数会在当前目录自动 init 一个实例，这样会造成用户的 abtnode 实例管理起来很混乱
- 优先考虑第三种方案

**Comment by LancelotLewis** [comment]
根据项目当前的具体情况，只在终端的信息及文档中做指引，不提供全自动化的流程
