### ISSUE TITLE
README 推荐的 pnpm create-blocklet test-blocklet 报错

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#55]
> robmao@roberts-imac work % pnpm create-blocklet test-blocklet
>  ERR_PNPM_NO_IMPORTER_MANIFEST_FOUND  No package.json (or package.yaml, or package.json5) was found in "/Users/robmao/work".
>

**Comment by mave99a** [comment]
npm 方式工作正常

**Comment by LancelotLewis** [comment]
fixed
`pnpm create-blocklet [name]` -> `pnpm create blocklet [name]`
