### ISSUE TITLE
`create-blocklet`直出的blocklet 不能直接执行`blocklet bundle`

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#57]
`create-blocklet`直出的blocklet 不能直接执行`blocklet bundle`

<img width="570" alt="image" src="https://user-images.githubusercontent.com/41923/152673243-794d7d13-9e12-4f0c-bc6c-e3ce2068c2bb.png">

我建议这种create-blocklet出来的东西应该所有全部可以直接执行，一路可以发布成为blocklet (虽然没有实际功能）但给用户非常流畅的全过程体验。

**Comment by LancelotLewis** [comment]
带有打包步骤的 blocklet 需要先执行打包命令，这个是由不同项目的特性而决定的，在每个生成的 blocklet 中提供了 `npm run bundle` 命令来帮助用户同时执行 打包和 `blocklet bundle`

**Comment by wangshijun** [comment]
文档里面有 cover，确实如 @LancelotLewis 所说
