### ISSUE TITLE
auth service 我觉得应该default 就有，只是问用户要不要完全被保护

### ISSUE THREAD

**Issue by mave99a** [blocklet/create-blocklet#72]
auth service 我觉得应该default 就有，只是问用户要不要完全被保护。 否则普通用户不可能理解这里的细节。 

<img width="312" alt="image" src="https://user-images.githubusercontent.com/41923/157553419-7428f297-cf85-4493-8eda-7ff155dc4b3a.png">

**Comment by linchen1987** [comment]
1.7.0 发布后，默认会有 auth service, blocklet.yml 中不需要主动声明

**Comment by LancelotLewis** [comment]
已跟随 blocklet server 1.7.0 升级
