### ISSUE TITLE
VI 系统更新相关工作

### ISSUE THREAD

**Issue by donotlb** [blocklet/create-blocklet#78]
相关 issue: https://github.com/ArcBlock/ux/issues/494  

- [ ] 升级 `@arcblock/ux` 到最新版本
- [ ] lato 字体
  - [ ] 检查 font-family 设置 (以及使用 roboto font 的地方), 如无必要, 建议去除 font-family 相关的代码, 最新的 theme 模块会优先使用 lato font, 并且已经引用了 font 资源
  - [ ] 检查页面内容 (英文内容) 是否正确应用了 lato font (控制台 - Elements - computed - Rendered Fonts)
  - [ ] 检查 font weight 的使用, 按最新的设计规范, 建议只使用 400 和 700 
  - [ ] 去除对 [fonts.googleapis.com/css?family=Roboto](http://fonts.googleapis.com/css?family=Roboto) 线上资源的引用 (如果有的话)
- [ ] Button 组件相关
  - [ ] 优先使用 ux Button 组件 (支持 `color="danger/warning"` 且 button 应该是 4px 的小圆角值), 替代 `@material-ui/core/Button` 
  - [ ] 基于 ButtonGroup 实现了 SplitButton 的地方, 可以直接使用 ux 的 SplitButton
  - [ ] 建议使用 `@material-ui/core/ButtonGroup` 替代 ux 的 ButtonGroup (应该是 4px 的小圆角值)
- [ ] colors 相关  
  theme 模块已经更新了最新的 primary/secondary color, 目前只有 blocklet store 和 launcher 需要覆盖 theme 默认的 primary/secondary color 
- [ ] DID Address 显示 did motif 
  除了像 explorer 交易列表这样存在大量 DID Address 的界面, 一般情况下 DID Address 前面应该显示 did motif, 可以通过给 DidAddress#prepend 设置一个 DidAvatar 组件来实现

**Comment by LancelotLewis** [comment]
create-blocklet 中未使用到 `@arcblock/ux` 包，在将来有使用相关模块时才需要更新
并且 create-blocklet 中会包含 react 以外的类库，所以不太适合做这部分工作
