### ISSUE TITLE
auth 和 email 出现了 undefined

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#79]
![image](https://user-images.githubusercontent.com/719985/159864496-18af5989-f9e2-478f-b39e-329457627450.png)

如果从所有可能的地方都找了，但是没有，可以试试看 blocklet config list，里面可能有（blocklet connect 写入的）

**Comment by LancelotLewis** [comment]
- 新增从 `blocklet config` 中获取 name 和 email
- 并且增加 name 和 email 必填的限制 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/8749615/160221619-896a3caa-30e1-4b60-bd59-b1ba54c8e6ea.png">

**Comment by LancelotLewis** [comment]
fixed by 2dc80ad46d460423a02ad360bea5f93e79e72348

**Comment by wangshijun** [comment]
我本地的环境

![Screen Shot 2022-03-30 at 17 32 17](https://user-images.githubusercontent.com/719985/160800105-8b5eddf3-22ec-44b2-9e51-b7361ecf216d.png)

![Screen Shot 2022-03-30 at 17 32 32](https://user-images.githubusercontent.com/719985/160800162-448a05ea-cadb-4208-a072-4fd11a373697.png)

**Comment by polunzh** [comment]
一样的问题:
![image](https://user-images.githubusercontent.com/4244426/160801471-17d2e07d-b826-4058-8623-744162682a98.png)

git config list:
![image](https://user-images.githubusercontent.com/4244426/160801838-435cf656-36e9-4050-a4ad-f115cae6d665.png)

npm config list:
![image](https://user-images.githubusercontent.com/4244426/160801969-3171bb0b-9a98-42fb-9219-d8c75e47b16c.png)

**Comment by wangshijun** [comment]
![Screen Shot 2022-03-30 at 17 42 20](https://user-images.githubusercontent.com/719985/160802195-8c13c2fd-904b-4c79-b9ea-535ce302375a.png)

@LancelotLewis 建议也支持下 blocklet connect 之后的结果，这里也有 name 和 email

**Comment by LancelotLewis** [comment]
> 建议也支持下 blocklet connect 之后的结果，这里也有 name 和 email，并且是用户提供给 store 的

支持了获取 default profile 的，貌似无法便捷的去获取用户当前所有的 profile

**Comment by LancelotLewis** [comment]
由于 nodejs 14.x 版本中的 npm 获取用户名及邮箱会默认返回一个 undefined，这个结果会变成一个字符串 “undefined”，针对于这种情况做了特殊处理

已修复
