### ISSUE TITLE
Bug bash: 20210802

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/create-blocklet#8]
在没有任何外界指导的情况下，通过文档去了解怎么使用该工具，以及使用该工具创建了项目之后，通过创建的项目中的文档去了解怎么去开发、打包、部署、发布该项目
Docs: https://github.com/blocklet/create-blocklet
Issues: Link to this one, [New issue](https://github.com/blocklet/create-blocklet/issues/new)

- [x]  dapp → react → none service @wangshijun 
- [x]  dapp → react → auth service @NateRobinson @LancelotLewis 
- [x]  static → react → none service @PaperHS 
- [x]  static → react → auth service @donotlb 
- [x]  本地开发成功
- [x]  本地打包成功
- [x]  本地部署成功
- [x]  本地发布成功（可以在本地部署一个 registry，再进行后续的操作）

**Comment by wangshijun** [comment]
第一步无法成功，暂缓
