### ISSUE TITLE
选择 pnpm 作为 client 时运行环境检查出现误报

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#80]
其实我本地有运行中的 server，不过不是用 pnpm 安装的 blocklet cli

![image](https://user-images.githubusercontent.com/719985/159864880-1b909b1c-67b1-48f8-a8c7-001b07af2641.png)

**Comment by LancelotLewis** [comment]
- 这个是使用哪个命令调用出现的 bug，`bn create` ? `blocklet create` ? `yarn/pnpm create blocklet`? `npm init blocklet`?
- 这个提示的表意是当前 blockelt-server 的版本太旧，由于使用了最新版的 auth-service 服务，所以要求最低版本需要是 1.7.0

**Comment by wangshijun** [comment]
验证了下，本地的 blocklet server 版本，pnpm 安装的是 1.6.23
