### ISSUE TITLE
创建 next.js 模版最后选择 pnpm 后报 husky 找不到

### ISSUE THREAD

**Issue by wangshijun** [blocklet/create-blocklet#81]
![Screen Shot 2022-03-25 at 08 20 21](https://user-images.githubusercontent.com/719985/160030599-afdb15a0-9c2f-451f-803b-04ff7265e524.png)

**Comment by LancelotLewis** [comment]
安装新版后即可正常工作

**Comment by LancelotLewis** [comment]
duplicate #89
