### ISSUE TITLE
路径可以高亮，避免和后面的省略号产生误解

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/create-blocklet#86]
![截屏2022-03-30 下午5 42 21](https://user-images.githubusercontent.com/12446758/160802251-dd4f4300-9fdc-484e-823d-fcf3c53e0cc0.png)

**Comment by NateRobinson** [comment]
https://github.com/ArcBlock/blocklet-server/issues/4532

**Comment by LancelotLewis** [comment]
fixed
