### ISSUE TITLE
安装依赖失败

### ISSUE THREAD

**Issue by polunzh** [blocklet/create-blocklet#89]
选择的 API 模板。

![image](https://user-images.githubusercontent.com/4244426/160804787-0a105539-8d4e-426d-93fc-efc74c88379a.png)

https://github.com/ArcBlock/blocklet-server/issues/4532

**Comment by LancelotLewis** [comment]
> 如今天沟通，把自动按装给去掉，怀疑是子进程里面安装导致的问题
