### ISSUE TITLE
[hold] bundle 报错

### ISSUE THREAD

**Issue by donotlb** [blocklet/create-blocklet#90]
环境:
- ubuntu 虚拟机
- 选择 fullstack & react

![image](https://user-images.githubusercontent.com/24994263/160805414-f6d8b2cd-1706-45ea-baf9-3357928acfdb.png)

https://github.com/ArcBlock/blocklet-server/issues/4532

**Comment by LancelotLewis** [comment]
出现问题的环境截图：
![image](https://user-images.githubusercontent.com/8749615/161363124-72becaae-f953-4d80-bf82-a183fcf87462.png)

创建了同样版本的虚拟机及 nodejs 版本，未复现该问题，先 hold

**Comment by LancelotLewis** [comment]
长期未出现该问题，应该不需要解决了，看是否可以 close @donotlb

**Comment by donotlb** [comment]
close 了
