### ISSUE TITLE
Upload 到 Store 后的提示有些乱

### ISSUE THREAD

**Issue by polunzh** [blocklet/create-blocklet#95]
下面红框内的信息可以合并为一条成功的信息？

![image](https://user-images.githubusercontent.com/4244426/160809271-c41f7cf7-1c9b-4b3a-b9da-d8e0090b6d26.png)

**Comment by polunzh** [comment]
https://github.com/ArcBlock/blocklet-server/issues/4532

**Comment by LancelotLewis** [comment]
fixed
