### ISSUE TITLE
基于 vue2 的模板创建的项目，upload 到 store 之后再下载安装打开，会 404 not found

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/create-blocklet#96]
![截屏2022-03-30 下午6 30 00](https://user-images.githubusercontent.com/12446758/160811541-c5f4c28d-ab83-4461-ad2a-e5c038710f05.png)

**Comment by NateRobinson** [comment]
https://github.com/ArcBlock/blocklet-server/issues/4532

**Comment by LancelotLewis** [comment]
vue-dapp 模板问题，已修复
