### ISSUE TITLE
尽量引导开发者使用 `blocklet dev` 去开发 blocklet 项目

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/create-blocklet#99]
- 将原有的 `npm run dev` 变更为 `npm run _dev`，然后将 `npm run dev` 设置为 `blocklet dev`
- 学习类似于 pnpm 中的限制机制，限制开发者必须使用 blocklet 命令来启动开发（不一定能实现）

**Comment by LancelotLewis** [comment]
目前每个项目都有的 scripts 有以下几种：
- dev
- build
- start
- bundle
 
blocklet dev 启动的命令都为 `npm run start`

可以将 `dev` 脚本设置为 `blocklet dev`，`start` 脚本设置为启动项目的命令，将 bundle 命令直接设置为原有的 build 命令的值，移除现有的 build 命令

一个可参考的例子为（static 模板）：
原有的脚本：
```json
{
  "dev": "craco start",
  "build": "craco build",
  "start": "npm run dev",
  "bundle": "npm run build"
}
```

改进后的脚本：
``` json
{
  "dev": "blocklet dev",
  "start": "craco start",
  "bundle": "craco build"
}
```

dapp 模板与 api 模板也参考上述的模式进行修改

**Comment by frmachao** [comment]
原本 react dapp 的 package.json
```
     "dev": "craco start",
    "start": "npm-run-all --parallel start:*",
    "start:client": "npm run dev",
    "start:api": "NODE_ENV=development nodemon api/index.js -w api",
```

改进后的：
```
     "dev": "blocklet dev",
    "start": "npm-run-all --parallel start:*",
    "start:client": "craco start",
    "start:api": "NODE_ENV=development nodemon api/index.js -w api",
```
